# Generated by Django 2.0 on 2019-09-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190909_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img_link',
            field=models.ImageField(default='', max_length=255, upload_to='front_img/', verbose_name='封面图片'),
        ),
    ]
